export {default as Bandobast} from './Bandobast';
export {default as Dashboard} from './Dashboard';
export {default as Admin} from './Admin';
export {default as Hardware} from './Hardware';
export {default as Personnel} from './Personnel';
export {default as Setting} from './Setting';
export {default as Login} from './Login';
export {default as Monitor} from './Dashboard/Monitor';
export {default as DetailedMap} from './Dashboard/DetailedMap';