export {default as Footer} from './Footer';
export {default as Header} from './Header';
export {default as Logo} from './Logo';
export {default as Navbar} from './Navbar';
export {default as Sidebar} from './Sidebar';
export {default as UserProfile} from './UserProfile';
export {default as OngoingDutyCard} from './OngoingDutyCard';
export {default as DutyCard } from './DutyCard';
export {default as TitlePersonal} from './TitlePersonal';
export {default as LocationTime} from './LocationTime'; 
export {default as Map} from './Map';
export {default as PersonnelRegForm} from './personnelRegForm';